vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images/uploads
            upload_destination: '%kernel.project_dir%/public/images/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
